name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot==20.3 PyGithub==2.6.1
    
    - name: Create log directory
      run: mkdir -p logs
    
    - name: Run bot
      run: |
        python bot.py >> logs/bot.log 2>&1
      working-directory: ${{ github.workspace }}

    - name: Upload logs if failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: bot-logs
        path: logs/bot.log